"""
External / attributed recipes — favorites from the web, posted under the cookbook account.

source_type:
  "external"  — from a website, source_url set to the original page
  "credit"    — from a cookbook, source_credit set to "Author, Book Title"
"""

RECIPES = [

    # ── Serious Eats ──────────────────────────────────────────────────────────

    {
        "author": "cookbook",
        "title": "3-Ingredient Stovetop Mac and Cheese",
        "description": "Pasta cooked in just enough water, then finished with evaporated milk and cheddar for a silky sauce — no roux needed.",
        "cook_time_minutes": 15,
        "servings": 2,
        "difficulty": "easy",
        "self_rating": 5,
        "source_type": "external",
        "source_url": "https://www.seriouseats.com/ingredient-stovetop-mac-and-cheese-recipe",
        "source_credit": None,
        "image_url": None,
        "tags": ["american", "vegetarian"],
        "ingredients": [
            {"quantity": "6",  "unit": "oz",  "name": "elbow macaroni"},
            {"quantity": "6",  "unit": "oz",  "name": "mild or medium cheddar cheese, grated"},
            {"quantity": "6",  "unit": "oz",  "name": "evaporated milk"},
            {"quantity": "",   "unit": "",    "name": "kosher salt"},
        ],
        "steps": [
            "Place the macaroni in a medium saucepan and add just enough cold water to cover. Season generously with salt and bring to a boil over high heat, stirring frequently.",
            "Cook, stirring often, until most of the water has been absorbed and the pasta is just shy of al dente, about 6 minutes.",
            "Add the evaporated milk and bring to a boil. Add the grated cheese and reduce heat to low. Cook, stirring constantly, until the cheese is fully melted and the sauce is smooth and creamy.",
            "Season with additional salt if needed and serve immediately.",
        ],
    },

    {
        "author": "cookbook",
        "title": "Pressure Cooker Corn Risotto",
        "description": "Corn three ways — cob-infused stock, blended corn purée, and whole kernels — for the most intensely corn-flavored risotto imaginable.",
        "cook_time_minutes": 40,
        "servings": 6,
        "difficulty": "medium",
        "self_rating": 5,
        "source_type": "external",
        "source_url": "https://www.seriouseats.com/pressure-cooker-corn-risotto",
        "source_credit": None,
        "image_url": None,
        "tags": ["italian", "vegetarian"],
        "ingredients": [
            {"quantity": "6",    "unit": "ears",  "name": "fresh corn"},
            {"quantity": "3.5",  "unit": "cups",  "name": "chicken or vegetable stock"},
            {"quantity": "1",    "unit": "",      "name": "bay leaf"},
            {"quantity": "3",    "unit": "sprigs","name": "fresh thyme"},
            {"quantity": "2",    "unit": "cloves","name": "garlic"},
            {"quantity": "2",    "unit": "",      "name": "shallots, minced"},
            {"quantity": "6",    "unit": "tbsp",  "name": "unsalted butter"},
            {"quantity": "2",    "unit": "cups",  "name": "arborio or carnaroli rice"},
            {"quantity": "3/4",  "unit": "cup",   "name": "dry white wine"},
            {"quantity": "1",    "unit": "tsp",   "name": "ground turmeric"},
            {"quantity": "1/4",  "unit": "cup",   "name": "heavy cream"},
            {"quantity": "1/2",  "unit": "cup",   "name": "Pecorino Romano, grated"},
            {"quantity": "",     "unit": "",      "name": "kosher salt and freshly ground black pepper"},
        ],
        "steps": [
            "Strip the corn kernels from the cobs. Use the back of a knife to scrape every drop of starchy corn milk from the cobs.",
            "Combine the corn cobs, stock, bay leaf, and thyme in a saucepan. Simmer for 15 minutes to make corn-infused stock. Strain and discard solids.",
            "Blend half the corn kernels with a splash of the corn stock until smooth to make a corn purée. Set aside.",
            "Using the sauté function on the pressure cooker, melt 4 tablespoons butter over medium heat. Add shallots and garlic and cook until softened, 3 to 4 minutes.",
            "Add rice and turmeric and stir to coat. Add wine and cook, stirring, until absorbed.",
            "Add 3 cups of the warm corn stock. Seal the pressure cooker and cook on high pressure for 6 minutes. Quick-release the pressure.",
            "Stir in the corn purée, remaining corn kernels, cream, Pecorino, and remaining butter. Fold gently until creamy. Season with salt and pepper and serve immediately.",
        ],
    },

    {
        "author": "cookbook",
        "title": "Salmon Burgers with Rémoulade and Fennel Slaw",
        "description": "Hand-chopped salmon burgers with crispy exteriors and medium-rare centers, piled on brioche with briny rémoulade and a fennel-radicchio slaw.",
        "cook_time_minutes": 40,
        "servings": 4,
        "difficulty": "medium",
        "self_rating": 5,
        "source_type": "external",
        "source_url": "https://www.seriouseats.com/salmon-burgers-remoulade-fennel-slaw-recipe",
        "source_credit": None,
        "image_url": None,
        "tags": ["american"],
        "ingredients": [
            # Salmon patties
            {"quantity": "1.5",  "unit": "lbs",  "name": "boneless skinless salmon, very finely hand-chopped"},
            {"quantity": "3",    "unit": "tbsp",  "name": "mixed fresh parsley, tarragon, and chives, minced"},
            {"quantity": "1/4",  "unit": "tsp",   "name": "ground coriander"},
            {"quantity": "1",    "unit": "inch",  "name": "fresh ginger, peeled and grated"},
            {"quantity": "",     "unit": "",      "name": "kosher salt and freshly ground black pepper"},
            # Rémoulade
            {"quantity": "1/2",  "unit": "cup",  "name": "mayonnaise"},
            {"quantity": "1",    "unit": "tbsp", "name": "brined capers, drained and minced"},
            {"quantity": "4",    "unit": "",     "name": "cornichons, minced"},
            {"quantity": "2.5",  "unit": "tsp",  "name": "mixed fresh parsley, tarragon, and chives, minced"},
            {"quantity": "2",    "unit": "tsp",  "name": "fresh lemon juice"},
            {"quantity": "1",    "unit": "tsp",  "name": "Dijon mustard"},
            {"quantity": "1/2",  "unit": "tsp",  "name": "prepared horseradish"},
            # Fennel slaw
            {"quantity": "1.75", "unit": "oz",   "name": "celery root, peeled and julienned"},
            {"quantity": "1.75", "unit": "oz",   "name": "radicchio, shredded"},
            {"quantity": "1.75", "unit": "oz",   "name": "fennel, thinly sliced"},
            {"quantity": "",     "unit": "",     "name": "extra-virgin olive oil, to coat"},
            {"quantity": "",     "unit": "",     "name": "fresh lemon juice, to taste"},
            # Assembly
            {"quantity": "4",    "unit": "",     "name": "brioche buns, toasted"},
        ],
        "steps": [
            "Make the rémoulade: combine mayonnaise, capers, cornichons, herbs, lemon juice, mustard, and horseradish in a small bowl. Season with salt and pepper. Refrigerate.",
            "Make the slaw: toss celery root, radicchio, and fennel together. Drizzle with olive oil and squeeze over lemon juice to taste. Season and set aside.",
            "Make the patties: combine the hand-chopped salmon with herbs, coriander, and ginger. Season well with salt and pepper. Form into 4 patties.",
            "Heat a skillet or grill pan over high heat. Cook the patties 2–3 minutes per side for medium-rare to medium — they should be lightly charred on the outside.",
            "Spread rémoulade on the toasted buns. Top with a salmon patty and a handful of fennel slaw. Serve immediately.",
        ],
    },

    {
        "author": "cookbook",
        "title": "5-Minute Miso-Glazed Toaster Oven Salmon",
        "description": "A miso-sake marinade transforms salmon into something restaurant-quality in minutes under the broiler.",
        "cook_time_minutes": 35,
        "servings": 4,
        "difficulty": "easy",
        "self_rating": 5,
        "source_type": "external",
        "source_url": "https://www.seriouseats.com/miso-glazed-salmon-in-the-toaster-oven-recipe",
        "source_credit": None,
        "image_url": None,
        "tags": ["japanese"],
        "ingredients": [
            {"quantity": "1/4", "unit": "cup",  "name": "red or white miso"},
            {"quantity": "1/3", "unit": "cup",  "name": "sake"},
            {"quantity": "1",   "unit": "tbsp", "name": "soy sauce"},
            {"quantity": "2",   "unit": "tbsp", "name": "vegetable oil"},
            {"quantity": "1/4", "unit": "cup",  "name": "sugar"},
            {"quantity": "4",   "unit": "5-6 oz fillets", "name": "skinless salmon, at least 1 inch thick"},
        ],
        "steps": [
            "Whisk together miso, sake, soy sauce, oil, and sugar until smooth. Rub the marinade over every surface of the salmon fillets.",
            "Transfer to a zip-lock bag or covered container and marinate for at least 30 minutes, or up to 2 days in the fridge.",
            "Preheat the broiler to high. Line a small broiler pan with foil.",
            "Remove salmon from the marinade, wiping off the excess (to prevent burning). Place on the prepared pan.",
            "Broil until the top surface is well charred and the salmon is barely warm in the center, about 5 minutes. Use foil to tent any spots that threaten to burn. Serve immediately.",
        ],
    },

    # ── NYT Cooking ───────────────────────────────────────────────────────────

    {
        "author": "cookbook",
        "title": "Salmon Roasted in Butter",
        "description": "Mark Bittman's legendary two-ingredient salmon — high heat, sizzling herb butter, and nothing else. Impossible to improve.",
        "cook_time_minutes": 15,
        "servings": 4,
        "difficulty": "easy",
        "self_rating": 5,
        "source_type": "external",
        "source_url": "https://cooking.nytimes.com/recipes/5703-salmon-roasted-in-butter",
        "source_credit": None,
        "image_url": None,
        "tags": ["american"],
        "ingredients": [
            {"quantity": "4",     "unit": "tbsp", "name": "unsalted butter (1/2 stick)"},
            {"quantity": "4",     "unit": "tbsp", "name": "fresh chervil, parsley, or dill, minced (divided)"},
            {"quantity": "1.5-2", "unit": "lbs",  "name": "thick salmon fillet (or 2 fillets)"},
            {"quantity": "",      "unit": "",     "name": "salt and freshly ground black pepper"},
            {"quantity": "",      "unit": "",     "name": "lemon wedges, for serving"},
        ],
        "steps": [
            "Heat the oven to 475°F. When the oven is hot, place the butter and half the herb in a roasting pan. Put the pan in the oven until the butter melts and the herb begins to sizzle, about 5 minutes.",
            "Add the salmon to the pan skin-side up. Roast for 4 minutes.",
            "Remove from the oven and peel off the skin. Season the exposed flesh with salt and pepper, then flip the fillet. Season again.",
            "Return to the oven and roast 3 to 5 more minutes, depending on the thickness and your preferred doneness.",
            "Spoon a little of the pan butter over each portion and garnish with the remaining herbs. Serve with lemon wedges.",
        ],
    },

    # ── Bon Appétit ───────────────────────────────────────────────────────────

    {
        "author": "cookbook",
        "title": "Vietnamese Tomato Salad",
        "description": "Peak-summer tomatoes tossed with fennel, herbs, and cucumber in a punchy fish sauce dressing, finished with crispy fried shallots and peanuts.",
        "cook_time_minutes": 15,
        "servings": 5,
        "difficulty": "easy",
        "self_rating": 5,
        "source_type": "external",
        "source_url": "https://www.bonappetit.com/recipe/vietnamese-tomato-salad",
        "source_credit": None,
        "image_url": None,
        "tags": ["vietnamese"],
        "ingredients": [
            {"quantity": "1/4",  "unit": "cup",  "name": "fish sauce (preferably Red Boat or Three Crabs)"},
            {"quantity": "1/4",  "unit": "cup",  "name": "fresh lime juice"},
            {"quantity": "1/4",  "unit": "cup",  "name": "sugar"},
            {"quantity": "1",    "unit": "tbsp", "name": "water"},
            {"quantity": "1",    "unit": "small","name": "fennel bulb, thinly sliced"},
            {"quantity": "1",    "unit": "",     "name": "Persian or kirby cucumber, halved and sliced into half-moons"},
            {"quantity": "1",    "unit": "",     "name": "Hungarian wax, Jimmy Nardello, or green bell pepper, seeded and sliced"},
            {"quantity": "1",    "unit": "small","name": "shallot, thinly sliced"},
            {"quantity": "1.5",  "unit": "lbs",  "name": "mixed heirloom tomatoes, halved or cut into wedges"},
            {"quantity": "2",    "unit": "cups", "name": "mixed tender herbs (dill, cilantro, and/or Thai basil), coarsely chopped"},
            {"quantity": "1/3",  "unit": "cup",  "name": "store-bought fried shallots"},
            {"quantity": "1/3",  "unit": "cup",  "name": "salted dry-roasted peanuts, crushed"},
            {"quantity": "",     "unit": "",     "name": "freshly ground black pepper"},
        ],
        "steps": [
            "Make the dressing: combine fish sauce, lime juice, sugar, and water in a jar. Cover and shake until the sugar is dissolved.",
            "Combine fennel, cucumber, pepper, raw shallot, tomatoes, and herbs in a large bowl. Season generously with black pepper.",
            "Drizzle about 1/2 cup of dressing over the salad and toss to combine. Taste and add more dressing if desired.",
            "Top with fried shallots and crushed peanuts just before serving.",
        ],
    },

    {
        "author": "cookbook",
        "title": "Spinach and Feta Cooked Like Saag Paneer",
        "description": "Priya Krishna's genius swap — salty feta instead of paneer — in a fragrant, weeknight-friendly saag from Indian-ish.",
        "cook_time_minutes": 30,
        "servings": 4,
        "difficulty": "easy",
        "self_rating": 5,
        "source_type": "external",
        "source_url": "https://www.bonappetit.com/story/saag-feta-indian-ish",
        "source_credit": None,
        "image_url": None,
        "tags": ["indian", "vegetarian", "gluten-free"],
        "ingredients": [
            {"quantity": "1/4",  "unit": "cup",  "name": "ghee or olive oil, plus 2 tbsp more (divided)"},
            {"quantity": "2",    "unit": "tbsp", "name": "coriander seeds"},
            {"quantity": "2",    "unit": "",     "name": "green cardamom pods"},
            {"quantity": "1",    "unit": "small","name": "yellow onion, diced"},
            {"quantity": "1",    "unit": "tbsp", "name": "fresh ginger, chopped"},
            {"quantity": "3",    "unit": "cloves","name": "garlic, minced"},
            {"quantity": "1",    "unit": "lb",   "name": "fresh baby spinach"},
            {"quantity": "1",    "unit": "small","name": "Indian green chile or serrano chile, chopped"},
            {"quantity": "1/2",  "unit": "tbsp", "name": "fresh lime juice"},
            {"quantity": "6",    "unit": "oz",   "name": "feta cheese, cut into 1/2-inch cubes"},
            {"quantity": "1",    "unit": "tsp",  "name": "cumin seeds"},
            {"quantity": "1/4",  "unit": "tsp",  "name": "asafetida (optional)"},
            {"quantity": "1/4",  "unit": "tsp",  "name": "red chile powder"},
            {"quantity": "",     "unit": "",     "name": "kosher salt"},
            {"quantity": "",     "unit": "",     "name": "rice or roti, for serving"},
        ],
        "steps": [
            "Heat 1/4 cup ghee in a large pan over medium heat. Add coriander seeds and cardamom pods and cook, stirring, for about 2 minutes until the seeds start to brown.",
            "Add the onion and cook until translucent, 5 to 6 minutes. Stir in the ginger and garlic and cook for 1 minute more.",
            "Add the spinach and cook until just wilted, 4 to 5 minutes. Remove from heat. Add the lime juice, green chile, and salt to taste.",
            "Let cool for 5 minutes. Transfer to a blender and blend into a chunky paste.",
            "Return the spinach mixture to the pan over low heat. Stir in 1/2 cup water, then gently fold in the feta cubes, being careful not to break them up.",
            "Make the tarka: in a small pan over medium-high heat, warm the remaining 2 tablespoons ghee for 1 minute. Add the cumin seeds. When they start to sputter and brown, about 1 minute, remove from heat. Immediately stir in the asafetida (if using) and red chile powder.",
            "Pour the tarka over the spinach and feta. Serve with rice or roti.",
        ],
    },

    # ── Food52 ────────────────────────────────────────────────────────────────

    {
        "author": "cookbook",
        "title": "Sticky Pomegranate & Black Pepper Chicken Wings",
        "description": "Oven-roasted wings glazed with pomegranate molasses, cracked black pepper, and warm spices — inspired by Persian fesenjan stew. From Sohla El-Waylly.",
        "cook_time_minutes": 90,
        "servings": 4,
        "difficulty": "medium",
        "self_rating": 5,
        "source_type": "external",
        "source_url": "https://food52.com/recipes/84961-pomegranate-chicken-wings-recipe",
        "source_credit": None,
        "image_url": None,
        "tags": ["american", "middle eastern"],
        "ingredients": [
            # Wings
            {"quantity": "2",   "unit": "lbs",  "name": "chicken wings"},
            {"quantity": "1",   "unit": "tbsp", "name": "kosher salt"},
            {"quantity": "1",   "unit": "tbsp", "name": "granulated sugar"},
            {"quantity": "2",   "unit": "tsp",  "name": "baking powder"},
            {"quantity": "1",   "unit": "tbsp", "name": "cornstarch"},
            # Pomegranate glaze
            {"quantity": "2",   "unit": "tbsp", "name": "neutral oil (grapeseed or canola)"},
            {"quantity": "1/4", "unit": "cup",  "name": "granulated sugar"},
            {"quantity": "2",   "unit": "tbsp", "name": "boiling water"},
            {"quantity": "1/2", "unit": "cup",  "name": "pomegranate molasses"},
            {"quantity": "2",   "unit": "tbsp", "name": "freshly ground black pepper"},
            {"quantity": "2",   "unit": "tsp",  "name": "salt"},
            {"quantity": "2",   "unit": "tsp",  "name": "ground cinnamon"},
            {"quantity": "1",   "unit": "tsp",  "name": "freshly grated nutmeg"},
            {"quantity": "1/2", "unit": "cup",  "name": "toasted walnut halves, roughly chopped"},
            {"quantity": "",    "unit": "",     "name": "flaky salt, to finish (optional)"},
        ],
        "steps": [
            "Pat the chicken wings dry and place in a large bowl. Combine salt, sugar, baking powder, and cornstarch, then toss with the wings until evenly coated. Arrange on a wire rack set over a foil-lined sheet pan. Refrigerate uncovered for at least 30 minutes (or overnight) to dry out the skin.",
            "Preheat oven to 350°F. Roast the wings for about 1 hour, flipping halfway through, until the skin is lightly browned and the fat has mostly rendered.",
            "Make the glaze: dissolve the sugar in the boiling water in a large bowl. Whisk in the oil, pomegranate molasses, black pepper, salt, cinnamon, and nutmeg.",
            "Increase the oven temperature to 375°F. Remove the wings, toss them in the glaze to coat, then return to the rack (reserving extra glaze in the bowl). Roast for another 20 minutes until charred and glossy.",
            "Transfer the finished wings back to the bowl with any remaining glaze. Add the chopped toasted walnuts and toss to coat. Finish with flaky salt if desired.",
        ],
    },

    {
        "author": "cookbook",
        "title": "Upside-Down Peach Mochi Cake",
        "description": "A gluten-free mochi cake with caramelized peaches — somewhere between sticky rice cake and upside-down cake. Dense, chewy, and impossible to stop eating.",
        "cook_time_minutes": 80,
        "servings": 9,
        "difficulty": "medium",
        "self_rating": 5,
        "source_type": "external",
        "source_url": "https://food52.com/recipes/86167-peach-upside-down-cake-recipe",
        "source_credit": None,
        "image_url": None,
        "tags": ["american", "gluten-free"],
        "ingredients": [
            {"quantity": "3",    "unit": "medium","name": "ripe peaches, quartered and pitted"},
            {"quantity": "3/4",  "unit": "cup",   "name": "granulated sugar (for caramel)"},
            {"quantity": "1/4",  "unit": "cup",   "name": "water (for caramel)"},
            {"quantity": "2",    "unit": "cups",  "name": "glutinous sweet rice flour (mochiko, e.g. Koda Farms Blue Star)"},
            {"quantity": "3/4",  "unit": "cup",   "name": "granulated sugar (for batter)"},
            {"quantity": "3/4",  "unit": "cup",   "name": "peach nectar or purée"},
            {"quantity": "3/4",  "unit": "cup",   "name": "heavy cream"},
            {"quantity": "2",    "unit": "large", "name": "eggs"},
            {"quantity": "1/4",  "unit": "cup",   "name": "unsalted butter, melted and cooled"},
            {"quantity": "1",    "unit": "tsp",   "name": "vanilla extract (or 1/2 vanilla bean pod, scraped)"},
            {"quantity": "1",    "unit": "tsp",   "name": "kosher salt"},
            {"quantity": "",     "unit": "",      "name": "flaky salt, to finish"},
        ],
        "steps": [
            "Preheat oven to 350°F. Butter an 8x8-inch brownie pan or 10-inch cast-iron skillet.",
            "Make the caramel: combine 3/4 cup sugar and 1/4 cup water in a saucepan. Cook over medium heat, stirring gently until mostly dissolved (1–2 minutes). Cover with a lid and simmer until just beginning to brown (3–5 minutes). Remove the lid and continue cooking until the sugar turns a deep amber (3–5 minutes). Pour immediately into the prepared pan and swirl to coat the bottom.",
            "Arrange the peach quarters cut-side down in a single layer on top of the caramel.",
            "Make the batter: whisk together the sweet rice flour, 3/4 cup sugar, and salt. In a separate bowl, whisk together the eggs, melted butter, peach nectar, heavy cream, and vanilla until smooth. Add the wet ingredients to the dry and whisk until homogenous.",
            "Pour the batter over the peaches. Bake for 55 to 65 minutes until deeply browned and the cake bounces back when gently pressed.",
            "Cool in the pan for 15 to 30 minutes. Run a knife around the edge, then invert onto a serving plate. Finish with flaky salt.",
        ],
    },

    {
        "author": "cookbook",
        "title": "French Onion Soup-fflé",
        "description": "Sohla El-Waylly's mashup of cheese soufflé and French onion soup — caramelized onions, beef broth gravy, and Gruyère baked in a breadcrumb-lined dish.",
        "cook_time_minutes": 60,
        "servings": 4,
        "difficulty": "hard",
        "self_rating": 5,
        "source_type": "external",
        "source_url": "https://food52.com/recipes/86372-french-onion-souffle-recipe",
        "source_credit": None,
        "image_url": None,
        "tags": ["french"],
        "ingredients": [
            {"quantity": "2",    "unit": "tbsp",  "name": "unsalted butter, plus more for greasing"},
            {"quantity": "2",    "unit": "tbsp",  "name": "plain dried breadcrumbs"},
            {"quantity": "2",    "unit": "large", "name": "yellow onions, thinly sliced"},
            {"quantity": "3/4",  "unit": "cup",   "name": "beef or chicken bone broth"},
            {"quantity": "1",    "unit": "tbsp",  "name": "all-purpose flour"},
            {"quantity": "4",    "unit": "large", "name": "eggs, separated"},
            {"quantity": "3",    "unit": "oz",    "name": "Gruyère cheese, grated (about 3/4 cup)"},
            {"quantity": "3/4",  "unit": "tsp",   "name": "kosher salt, divided"},
            {"quantity": "1/4",  "unit": "tsp",   "name": "freshly ground black pepper"},
            {"quantity": "1/4",  "unit": "tsp",   "name": "freshly grated nutmeg"},
        ],
        "steps": [
            "Butter a 1½-quart soufflé dish (or 4 large oven-safe mugs). Add the breadcrumbs and shake to coat all sides evenly. Tap out any excess.",
            "Melt the butter in a medium saucepan over medium heat. Add the onions and 1/2 tsp salt. Cook, stirring occasionally, until deeply caramelized and golden brown, 30 to 40 minutes.",
            "Stir in the flour and cook for 1 minute. Add the broth and bring to a boil, stirring, until you have a very thick gravy. Remove from heat and let cool slightly.",
            "Stir the egg yolks, Gruyère, remaining salt, pepper, and nutmeg into the onion mixture.",
            "In a clean bowl, beat the egg whites with a pinch of salt to stiff peaks. Fold the whites into the onion mixture in three additions, gently but thoroughly.",
            "Pour into the prepared dish. Bake at 425°F for 5 minutes, then reduce to 400°F and bake until risen, golden, and just set with a slight wobble in the center, 15 to 18 more minutes (12–15 minutes for individual mugs).",
            "Serve immediately — soufflés wait for no one.",
        ],
    },

]
