"""
Recipes submitted by friends — posted under their accounts.

Use source_type "original" for recipes they created themselves.
Set `author` to the friend's username (must match an entry in users.py).
"""

RECIPES = [

    # ── Julianne Cabour ───────────────────────────────────────────────────────
    {
        "author": "julianne",
        "title": "Sweet Potato Chorizo Chili with Poblano-Avocado Crema",
        "description": "Julianne's award winning chili circa 2014.",
        "cook_time_minutes": 90,
        "servings": 8,
        "difficulty": "medium",
        "self_rating": 5,
        "source_type": "external",
        "source_url": "https://hostthetoast.com/sweet-potato-chorizo-chili-with-poblano-avocado-crema-and-goat-cheese/",
        "source_credit": None,
        "image_url": "https://res.cloudinary.com/dioqhure1/image/upload/f_auto,q_auto,w_600,h_400,c_fill/chorizo-chili",
        "tags": ["american", "mexican"],
        "ingredients": [
            {"quantity": "2",    "unit": "large",       "name": "sweet potatoes"},
            {"quantity": "1",    "unit": "head",        "name": "garlic"},
            {"quantity": "2",    "unit": "",            "name": "poblano peppers"},
            {"quantity": "2",    "unit": "tbsp",        "name": "canola oil, divided"},
            {"quantity": "1",    "unit": "lb",          "name": "Mexican chorizo, uncooked"},
            {"quantity": "1",    "unit": "",            "name": "white onion, diced small"},
            {"quantity": "1",    "unit": "tbsp",        "name": "cumin"},
            {"quantity": "1",    "unit": "tsp",         "name": "smoked paprika"},
            {"quantity": "1/4",  "unit": "tsp",         "name": "cinnamon"},
            {"quantity": "2",    "unit": "cups",        "name": "chicken stock"},
            {"quantity": "1",    "unit": "14.5 oz can", "name": "fire-roasted diced tomatoes"},
            {"quantity": "1",    "unit": "",            "name": "chipotle pepper in adobo"},
            {"quantity": "1",    "unit": "15 oz can",   "name": "black beans, drained and rinsed"},
            {"quantity": "1",    "unit": "15 oz can",   "name": "hominy, drained and rinsed"},
            {"quantity": "4",    "unit": "tbsp",        "name": "tomato paste"},
            {"quantity": "",     "unit": "",            "name": "kosher salt and black pepper, to taste"},
            {"quantity": "1",    "unit": "",            "name": "avocado, pit and skin removed"},
            {"quantity": "2",    "unit": "",            "name": "limes, juiced"},
            {"quantity": "2",    "unit": "oz",          "name": "goat cheese, crumbled"},
            {"quantity": "",     "unit": "",            "name": "fresh cilantro, chopped, to top"},
            {"quantity": "",     "unit": "",            "name": "sliced radish, to top (optional)"},
        ],
        "steps": [
            "Preheat the oven to 400°F. Line a baking sheet with foil.",
            "Cut the papery top off the head of garlic to expose the cloves. Place the garlic, sweet potatoes, and poblano peppers on the prepared baking sheet and drizzle lightly with oil. Roast for 30 minutes, then let cool until you can easily handle the potatoes.",
            "Meanwhile, heat the remaining oil in a large pot over medium-high heat. Remove the chorizo from the casing and add to the pot. Break it apart as you would ground beef and cook until browned all over, about 5 minutes.",
            "Add the onion to the pot and sauté until translucent. Stir in the cumin, smoked paprika, and cinnamon and cook for 1 minute. Pour in the chicken stock and bring to a boil.",
            "Once the sweet potatoes and peppers are cool enough to handle, peel the skins from both — they should come off easily. Chop the sweet potato into bite-sized pieces. Stem and seed the poblano peppers.",
            "In a blender or food processor, combine the roasted garlic (squeezed out of its papery skin), 1 of the roasted poblanos, the chipotle pepper, and the diced tomatoes. Process until smooth. Pour into the pot and bring back to a boil. Let the liquid reduce slightly, then stir in the black beans, hominy, tomato paste, and chopped sweet potato. Reduce to a simmer and cook for 30 minutes. Season with salt and pepper.",
            "While the chili simmers, blend the remaining roasted poblano, avocado, and lime juice until smooth to make the crema. Serve the chili topped with a dollop of poblano-avocado crema, crumbled goat cheese, cilantro, and sliced radish.",
        ],
    },

    # ── Mike Sahl ─────────────────────────────────────────────────────────────
    {
        "author": "mike_sahl",
        "title": "Mike's Marvelous Mai Tai",
        "description": "Mike's legendary mai tai. Use less juice if you wanna get more fucked up.",
        "cook_time_minutes": 5,
        "servings": 1,
        "difficulty": "easy",
        "self_rating": 5,
        "source_type": "original",
        "source_url": None,
        "source_credit": None,
        "image_url": "https://res.cloudinary.com/dioqhure1/image/upload/f_auto,q_auto,w_600,h_400,c_fill/mai-tai",
        "tags": ["american"],
        "ingredients": [
            {"quantity": "1",   "unit": "oz",   "name": "dark rum"},
            {"quantity": "1",   "unit": "oz",   "name": "white rum"},
            {"quantity": "1/2", "unit": "oz",   "name": "coconut rum (preferably Malibu)"},
            {"quantity": "1/2", "unit": "oz",   "name": "orgeat"},
            {"quantity": "1/2", "unit": "oz",   "name": "triple sec"},
            {"quantity": "1",   "unit": "oz",   "name": "orange juice"},
            {"quantity": "2",   "unit": "oz",   "name": "pineapple juice"},
            {"quantity": "",    "unit": "",     "name": "dash of grenadine"},
            {"quantity": "",    "unit": "",     "name": "crushed ice or ice cubes"},
            {"quantity": "",    "unit": "",     "name": "lime wedge, pineapple wedge, or cherry for garnish (optional)"},
        ],
        "steps": [
            "Combine all ingredients in a cocktail shaker.",
            "Shake well and serve over crushed ice. If crushed ice isn't available, serve over a glass full of ice cubes.",
            "Garnish with a lime wedge, pineapple wedge, or cherry if you're tryin to get fancy.",
        ],
    },

    # ── Beth Lord ─────────────────────────────────────────────────────────────
    {
        "author": "beth",
        "title": "Jelly Almond Cookies",
        "description": "Beth's classic almond thumbprint cookies with jelly and an optional powdered sugar glaze.",
        "cook_time_minutes": 30,
        "servings": 24,
        "difficulty": "easy",
        "self_rating": 5,
        "source_type": "original",
        "source_url": None,
        "source_credit": None,
        "image_url": "https://res.cloudinary.com/dioqhure1/image/upload/f_auto,q_auto,w_600,h_400,c_fill/almond-cookies",
        "tags": ["american"],
        "ingredients": [
            {"quantity": "1/2",   "unit": "lb",    "name": "butter"},
            {"quantity": "1/8",   "unit": "tsp",   "name": "salt"},
            {"quantity": "1/4",   "unit": "tsp",   "name": "almond extract"},
            {"quantity": "1/2",   "unit": "cup",   "name": "sugar"},
            {"quantity": "1",     "unit": "",      "name": "egg yolk"},
            {"quantity": "2 3/4", "unit": "cups",  "name": "flour, sifted"},
            {"quantity": "",      "unit": "",      "name": "jelly (any flavor)"},
            {"quantity": "1",     "unit": "cup",   "name": "confectioners sugar (for glaze, optional)"},
            {"quantity": "1",     "unit": "tbsp",  "name": "boiling water (for glaze, optional)"},
        ],
        "steps": [
            "Preheat oven to 375°F. Use the top oven rack.",
            "Cream together butter, salt, and almond extract until light and fluffy.",
            "Beat in the sugar, then the egg yolk.",
            "Gradually add the sifted flour, mixing until the dough just holds together.",
            "Roll dough into balls and place on an ungreased cookie sheet.",
            "Press a knuckle into the center of each ball and fill the hole with jelly.",
            "Bake 15–17 minutes until lightly golden.",
            "Optional glaze: stir confectioners sugar into boiling water off the heat until it looks like heavy cream. Brush or spoon over cookies as they cool.",
        ],
    },

    # ── Masha Shapiro ─────────────────────────────────────────────────────────
    {
        "author": "masha",
        "title": "Masha's Delicious Smoothie",
        "description": "Masha's go-to smoothie.",
        "cook_time_minutes": 5,
        "servings": 1,
        "difficulty": "easy",
        "self_rating": 5,
        "source_type": "original",
        "source_url": None,
        "source_credit": None,
        "image_url": "https://res.cloudinary.com/dioqhure1/image/upload/f_auto,q_auto,w_600,h_400,c_fill/smoothie",
        "tags": ["vegan", "gluten-free", "dairy-free"],
        "ingredients": [
            {"quantity": "1",   "unit": "handful", "name": "mango"},
            {"quantity": "1",   "unit": "handful", "name": "berries"},
            {"quantity": "1/2", "unit": "",        "name": "banana"},
            {"quantity": "1",   "unit": "cup",     "name": "almond milk"},
            {"quantity": "1",   "unit": "tbsp",    "name": "plain yogurt"},
            {"quantity": "1",   "unit": "tsp",     "name": "honey"},
            {"quantity": "1/2", "unit": "tsp",     "name": "vanilla extract"},
            {"quantity": "1",   "unit": "pinch",   "name": "cinnamon"},
        ],
        "steps": [
            "Add all ingredients to a blender and blend until smooth. Drink immediately.",
        ],
    },
    {
        "author": "masha",
        "title": "Masha's Everything Salad",
        "description": "Masha's assembly-only salad. No real recipe — just pile on what you have.",
        "cook_time_minutes": 10,
        "servings": 2,
        "difficulty": "easy",
        "self_rating": 5,
        "source_type": "original",
        "source_url": None,
        "source_credit": None,
        "image_url": "https://res.cloudinary.com/dioqhure1/image/upload/f_auto,q_auto,w_600,h_400,c_fill/everything-salad",
        "tags": ["vegetarian", "mediterranean"],
        "ingredients": [
            {"quantity": "",  "unit": "",   "name": "spinach"},
            {"quantity": "",  "unit": "",   "name": "pickled beets (or Trader Joe's roasted beets)"},
            {"quantity": "",  "unit": "",   "name": "cucumber, sliced"},
            {"quantity": "",  "unit": "",   "name": "cherry tomatoes"},
            {"quantity": "",  "unit": "",   "name": "corn"},
            {"quantity": "",  "unit": "",   "name": "chickpeas"},
            {"quantity": "",  "unit": "",   "name": "artichoke hearts (optional)"},
            {"quantity": "",  "unit": "",   "name": "couscous, cooked"},
            {"quantity": "",  "unit": "",   "name": "feta cheese or goat cheese"},
            {"quantity": "",  "unit": "",   "name": "olive oil"},
            {"quantity": "",  "unit": "",   "name": "salt and pepper"},
        ],
        "steps": [
            "Combine all ingredients in a large bowl. Drizzle with olive oil and season with salt and pepper.",
            "Serve cold.",
        ],
    },
    {
        "author": "masha",
        "title": "15-Minute Creamy Tomato Soup",
        "description": "Weeknight tomato soup that comes together in 15 minutes, blended silky smooth.",
        "cook_time_minutes": 15,
        "servings": 5,
        "difficulty": "easy",
        "self_rating": 5,
        "source_type": "external",
        "source_url": "https://www.seriouseats.com/recipes/2012/02/15-minute-creamy-tomato-soup-vegan-recipe.html",
        "source_credit": None,
        "image_url": "https://res.cloudinary.com/dioqhure1/image/upload/f_auto,q_auto,w_600,h_400,c_fill/tomato-soup",
        "tags": ["vegan", "vegetarian", "dairy-free"],
        "ingredients": [
            {"quantity": "1/2", "unit": "cup",  "name": "extra-virgin olive oil, divided"},
            {"quantity": "2",   "unit": "",     "name": "garlic cloves, grated"},
            {"quantity": "1",   "unit": "small","name": "onion, finely sliced (about 1 cup)"},
            {"quantity": "1",   "unit": "tsp",  "name": "dried oregano"},
            {"quantity": "1/2", "unit": "tsp",  "name": "red pepper flakes"},
            {"quantity": "2",   "unit": "slices","name": "white bread, crusts removed, torn into 1/2-inch pieces"},
            {"quantity": "2",   "unit": "28 oz cans", "name": "whole peeled tomatoes packed in juice"},
            {"quantity": "",    "unit": "",     "name": "kosher salt and freshly ground black pepper"},
            {"quantity": "",    "unit": "",     "name": "minced chives, basil, or parsley for garnish"},
            {"quantity": "",    "unit": "",     "name": "toasted bread or grilled cheese for serving"},
        ],
        "steps": [
            "Heat 2 tablespoons of olive oil in a large saucepan over medium-high heat until shimmering. Add garlic, onion, oregano, and red pepper flakes. Cook, stirring frequently, until onions are softened but not browned, about 4 minutes.",
            "Add the bread and tomatoes. Roughly mash the tomatoes with a whisk or potato masher. Add 2 cups water. Bring to a boil over high heat, then reduce to a simmer and cook for 5 minutes.",
            "Transfer half the soup to a blender. Blend starting at low speed and gradually increasing to high — hold a kitchen towel over the vent lid to prevent blowout. With the blender running on high, trickle in half the remaining olive oil. Season with salt and pepper.",
            "Transfer to a large bowl and repeat with the remaining half of the soup and olive oil.",
            "Ladle into bowls, top with minced herbs, drizzle with olive oil, and serve with toast or grilled cheese.",
        ],
    },

    # ── Cody Snell ────────────────────────────────────────────────────────────
    {
        "author": "cody",
        "title": "Sweet Potato Crunch Casserole",
        "description": "A crowd-pleasing holiday casserole with a brown sugar pecan crunch topping.",
        "cook_time_minutes": 90,
        "servings": 12,
        "difficulty": "easy",
        "self_rating": 5,
        "source_type": "original",
        "source_url": None,
        "source_credit": None,
        "image_url": "https://res.cloudinary.com/dioqhure1/image/upload/f_auto,q_auto,w_600,h_400,c_fill/sweet-potato-casserole",
        "tags": ["american"],
        "ingredients": [
            # Casserole
            {"quantity": "5-6",  "unit": "medium", "name": "sweet potatoes"},
            {"quantity": "3",    "unit": "",       "name": "eggs"},
            {"quantity": "1",    "unit": "cup",    "name": "sugar"},
            {"quantity": "1/2",  "unit": "cup",    "name": "margarine, melted"},
            {"quantity": "1/2",  "unit": "cup",    "name": "milk"},
            {"quantity": "2",    "unit": "tsp",    "name": "vanilla extract"},
            # Topping
            {"quantity": "1",    "unit": "cup",    "name": "brown sugar"},
            {"quantity": "1/2",  "unit": "cup",    "name": "flour"},
            {"quantity": "1",    "unit": "cup",    "name": "pecans, chopped"},
            {"quantity": "1/2",  "unit": "cup",    "name": "margarine, melted (for topping)"},
        ],
        "steps": [
            "Preheat oven to 350°F.",
            "Peel and boil sweet potatoes in a large pot of water until a fork glides through easily. Drain in a colander, return to the pot, and mash until smooth.",
            "Mix in the eggs, sugar, milk, margarine, and vanilla until well blended.",
            "Pour mixture into a standard 15x9-inch baking pan (no need to butter or spray the bottom).",
            "In a separate bowl, mix together the brown sugar, flour, pecans, and melted margarine for the topping.",
            "Evenly cover the casserole with the topping mixture — it's fine to use your hands.",
            "Bake for 1 hour.",
        ],
    },

    # ── Jocelyn ───────────────────────────────────────────────────────────────
    {
        "author": "jocelyn",
        "title": "Classy Bitch Cocktail",
        "description": "Jocelyn's elegant gin cocktail. Crisp, citrusy, and perfectly balanced.",
        "cook_time_minutes": 5,
        "servings": 1,
        "difficulty": "easy",
        "self_rating": 5,
        "source_type": "original",
        "source_url": None,
        "source_credit": None,
        "image_url": "https://res.cloudinary.com/dioqhure1/image/upload/f_auto,q_auto,w_600,h_400,c_fill/classy-bitch",
        "tags": ["american"],
        "ingredients": [
            {"quantity": "1",  "unit": "shot", "name": "good gin"},
            {"quantity": "2",  "unit": "tbsp", "name": "grapefruit juice"},
            {"quantity": "2",  "unit": "tbsp", "name": "simple syrup"},
            {"quantity": "",   "unit": "",     "name": "club soda, to top"},
            {"quantity": "1",  "unit": "sprig","name": "fresh rosemary"},
        ],
        "steps": [
            "Combine gin, grapefruit juice, and simple syrup in a shaker with ice. Shake well.",
            "Strain into a glass and top with club soda.",
            "Garnish with a sprig of rosemary.",
        ],
    },

    # ── Carolyn Wright ────────────────────────────────────────────────────────
    {
        "author": "carolyn",
        "title": "Special K Bars",
        "description": "Carolyn's no-bake peanut butter bars with a chocolate-butterscotch topping. Always a hit.",
        "cook_time_minutes": 30,
        "servings": 24,
        "difficulty": "easy",
        "self_rating": 5,
        "source_type": "original",
        "source_url": None,
        "source_credit": None,
        "image_url": "https://res.cloudinary.com/dioqhure1/image/upload/f_auto,q_auto,w_600,h_400,c_fill/special-k-bars",
        "tags": ["american"],
        "ingredients": [
            {"quantity": "1",   "unit": "cup",  "name": "light corn syrup"},
            {"quantity": "1",   "unit": "cup",  "name": "sugar"},
            {"quantity": "1",   "unit": "cup",  "name": "creamy peanut butter"},
            {"quantity": "6",   "unit": "cups", "name": "Special K cereal (or Rice Krispies)"},
            {"quantity": "1",   "unit": "cup",  "name": "milk chocolate chips"},
            {"quantity": "1",   "unit": "cup",  "name": "butterscotch chips"},
            {"quantity": "1/2", "unit": "cup",  "name": "butter"},
        ],
        "steps": [
            "In a saucepan over medium heat, melt together the corn syrup and sugar, stirring until the sugar is dissolved. Do not let it boil.",
            "Remove from heat and stir in the peanut butter until smooth.",
            "Stir in the Special K cereal until fully coated.",
            "Press mixture evenly into a greased 9x13 pan. A buttered spoon works well for spreading.",
            "Melt the chocolate chips, butterscotch chips, and butter together in a microwave-safe bowl in 30-second intervals, stirring between each, until fully melted.",
            "Spread the chocolate topping evenly over the bars.",
            "Refrigerate until hardened. Cut into squares and serve.",
        ],
    },

    # ── GTR ───────────────────────────────────────────────────────────────────
    {
        "author": "gtr",
        "title": "Geoff's Dank Guac",
        "description": "GTR's go-to guacamole. Refrigerate with the avocado pits to keep it fresh.",
        "cook_time_minutes": 15,
        "servings": 8,
        "difficulty": "easy",
        "self_rating": 5,
        "source_type": "original",
        "source_url": None,
        "source_credit": None,
        "image_url": "https://res.cloudinary.com/dioqhure1/image/upload/f_auto,q_auto,w_600,h_400,c_fill/guac",
        "tags": ["mexican", "vegan", "gluten-free", "dairy-free"],
        "ingredients": [
            {"quantity": "6",  "unit": "",      "name": "perfectly ripe avocados"},
            {"quantity": "2",  "unit": "",      "name": "fresh limes, juiced"},
            {"quantity": "2",  "unit": "tsp",   "name": "salt"},
            {"quantity": "1",  "unit": "cup",   "name": "red onion, diced"},
            {"quantity": "6",  "unit": "tbsp",  "name": "fresh cilantro, chopped"},
            {"quantity": "4",  "unit": "",      "name": "plum tomatoes, diced"},
            {"quantity": "5",  "unit": "tsp",   "name": "garlic, minced"},
            {"quantity": "2",  "unit": "pinches","name": "ground cayenne pepper"},
        ],
        "steps": [
            "In a medium bowl, mash together the avocados, lime juice, and salt.",
            "Mix in the red onion, cilantro, tomatoes, and garlic.",
            "Stir in the cayenne pepper.",
            "Refrigerate for at least 1 hour for best flavor. To keep fresh in the fridge, store with at least half of the avocado pits submerged in the guacamole.",
        ],
    },

    # ── Keith ─────────────────────────────────────────────────────────────────
    {
        "author": "keith",
        "title": "Keith's Kranberry Relish",
        "description": "A Thanksgiving staple. Bright, fresh, and nothing like the canned stuff.",
        "cook_time_minutes": 15,
        "servings": 8,
        "difficulty": "easy",
        "self_rating": 5,
        "source_type": "original",
        "source_url": None,
        "source_credit": None,
        "image_url": "https://res.cloudinary.com/dioqhure1/image/upload/f_auto,q_auto,w_600,h_400,c_fill/cranberry-relish",
        "tags": ["american", "vegan", "gluten-free", "dairy-free"],
        "ingredients": [
            {"quantity": "1",  "unit": "bag",  "name": "fresh cranberries"},
            {"quantity": "1",  "unit": "whole","name": "orange (including peel/zest), cut into 1-inch pieces"},
            {"quantity": "",   "unit": "",     "name": "sugar, to taste"},
        ],
        "steps": [
            "Rinse the cranberries and add them to a food processor.",
            "Cut the orange into small pieces (about 1 inch), including the peel and zest. Add to the food processor.",
            "Pulse at a medium setting until the cranberries and orange reach your desired consistency.",
            "Add sugar to taste throughout the process, pulsing to combine.",
        ],
    },

    # ── Zach Knowles ──────────────────────────────────────────────────────────
    {
        "author": "zach",
        "title": "Zach's Peanut Noodles",
        "description": "Quick peanut noodles with a sauce you can dial up or down. Great cold or hot.",
        "cook_time_minutes": 20,
        "servings": 4,
        "difficulty": "easy",
        "self_rating": 5,
        "source_type": "original",
        "source_url": None,
        "source_credit": None,
        "image_url": "https://res.cloudinary.com/dioqhure1/image/upload/f_auto,q_auto,w_600,h_400,c_fill/peanut-noodles",
        "tags": ["american"],
        "ingredients": [
            {"quantity": "1",   "unit": "lb",   "name": "pasta (fettuccine, linguine, or soba recommended)"},
            {"quantity": "1",   "unit": "cup",  "name": "chunky peanut butter"},
            {"quantity": "3",   "unit": "tbsp", "name": "soy sauce"},
            {"quantity": "1/2", "unit": "cup",  "name": "rice wine vinegar"},
            {"quantity": "1",   "unit": "tbsp", "name": "brown sugar or honey"},
            {"quantity": "1",   "unit": "tbsp", "name": "Sambal Oelek, Sriracha, or Gochujang"},
            {"quantity": "1",   "unit": "clove","name": "garlic, grated"},
            {"quantity": "1",   "unit": "tbsp", "name": "fresh ginger root, grated"},
            {"quantity": "1",   "unit": "tsp",  "name": "sesame oil"},
            {"quantity": "",    "unit": "",     "name": "lime wedges, scallions, cilantro, and crushed peanuts for garnish"},
        ],
        "steps": [
            "Boil pasta to al dente according to package directions.",
            "While the pasta cooks, whisk together the peanut butter, soy sauce, rice wine vinegar, brown sugar, chili sauce, garlic, ginger, and sesame oil to make the sauce. If too thick, add hot water; if too thin, add more peanut butter.",
            "Drain the pasta and toss with the sauce until well coated.",
            "Garnish with lime wedges, scallions, cilantro, and crushed peanuts. Serve hot or at room temperature.",
        ],
    },

    # ── Rachel & Mike ─────────────────────────────────────────────────────────
    {
        "author": "rachel_and_mike",
        "title": "Lasagna with Big Sauce",
        "description": "Rachel & Mike's Sunday lasagna with a vegetable-packed, slow-simmered big sauce.",
        "cook_time_minutes": 120,
        "servings": 10,
        "difficulty": "medium",
        "self_rating": 5,
        "source_type": "original",
        "source_url": None,
        "source_credit": None,
        "image_url": "https://res.cloudinary.com/dioqhure1/image/upload/f_auto,q_auto,w_600,h_400,c_fill/lasagna",
        "tags": ["italian", "american"],
        "ingredients": [
            # Big Sauce
            {"quantity": "1",   "unit": "small can", "name": "tomato paste"},
            {"quantity": "3",   "unit": "large",     "name": "tomatoes, blanched, peeled, and rough chopped"},
            {"quantity": "1/2", "unit": "large",     "name": "red onion"},
            {"quantity": "4",   "unit": "cloves",    "name": "garlic, minced"},
            {"quantity": "3",   "unit": "",          "name": "carrots, diced small"},
            {"quantity": "2",   "unit": "cups",      "name": "broccoli, chopped"},
            {"quantity": "1",   "unit": "",          "name": "bell pepper, diced"},
            {"quantity": "1",   "unit": "cup",       "name": "chicken broth (or water), approximately"},
            {"quantity": "",    "unit": "",          "name": "salt, pepper, basil, oregano to taste"},
            {"quantity": "1",   "unit": "lb",        "name": "ground beef (or pork or turkey)"},
            # Assembly
            {"quantity": "1/4", "unit": "cup",       "name": "pecorino cheese, finely shredded"},
            {"quantity": "1.5", "unit": "cups",      "name": "ricotta cheese"},
            {"quantity": "1",   "unit": "",          "name": "egg"},
            {"quantity": "",    "unit": "",          "name": "garlic powder and parsley to season ricotta"},
            {"quantity": "9",   "unit": "",          "name": "standard lasagna noodles, cooked per package directions"},
            {"quantity": "2",   "unit": "cups",      "name": "shredded mozzarella cheese"},
            {"quantity": "",    "unit": "",          "name": "olive oil, for sautéing"},
        ],
        "steps": [
            "Sauté all the vegetables (onion, garlic, carrots, broccoli, bell pepper) in olive oil in a large pot until soft.",
            "Add the chopped tomatoes and tomato paste, then slowly stir in broth until you reach your desired consistency. Season with salt, pepper, basil, and oregano to taste — add a pinch of sugar if needed.",
            "In a separate pan, crumble and cook the ground beef until browned. Add the meat to the tomato sauce.",
            "Simmer the sauce for 30 minutes to let the flavors meld. Stir in the pecorino cheese until melted and fully incorporated — the sauce should turn a nice orange color.",
            "In a bowl, mix the ricotta with the egg and season with garlic powder and parsley.",
            "Preheat oven to 375°F. Spread a thin layer of sauce on the bottom of a casserole dish to prevent sticking.",
            "Layer cooked noodles, seasoned ricotta, big sauce, and shredded mozzarella. Repeat until you've used everything up.",
            "Top with mozzarella and bake uncovered at 375°F for 30–35 minutes, until the top is golden brown.",
        ],
    },

    # ── Sonia Verma ───────────────────────────────────────────────────────────
    {
        "author": "sonia",
        "title": "Sonia's Butter Chicken",
        "description": "Sonia's from-scratch butter chicken with homemade tandoori chicken. Pair with basmati rice or naan.",
        "cook_time_minutes": 90,
        "servings": 6,
        "difficulty": "hard",
        "self_rating": 5,
        "source_type": "original",
        "source_url": None,
        "source_credit": None,
        "image_url": "https://res.cloudinary.com/dioqhure1/image/upload/f_auto,q_auto,w_600,h_400,c_fill/butter-chicken",
        "tags": ["indian"],
        "ingredients": [
            # Tandoori Chicken Marinade
            {"quantity": "2",   "unit": "lbs",   "name": "boneless chicken thighs or breasts, cubed"},
            {"quantity": "2",   "unit": "tbsp",  "name": "ginger garlic paste"},
            {"quantity": "1",   "unit": "tsp",   "name": "ground cumin"},
            {"quantity": "1/2", "unit": "tsp",   "name": "ground cardamom"},
            {"quantity": "1/2", "unit": "tsp",   "name": "cayenne pepper"},
            {"quantity": "1",   "unit": "tbsp",  "name": "paprika"},
            {"quantity": "1",   "unit": "tbsp",  "name": "garam masala"},
            {"quantity": "1/3", "unit": "cup",   "name": "plain yogurt"},
            {"quantity": "1",   "unit": "",      "name": "lemon, juiced"},
            # Butter Chicken Sauce
            {"quantity": "2",   "unit": "cups",  "name": "canned pureed tomatoes"},
            {"quantity": "2-3", "unit": "small", "name": "green chilies"},
            {"quantity": "3",   "unit": "tbsp",  "name": "ginger garlic paste"},
            {"quantity": "1",   "unit": "stick", "name": "butter"},
            {"quantity": "1",   "unit": "tbsp",  "name": "ground cumin"},
            {"quantity": "1",   "unit": "tbsp",  "name": "paprika"},
            {"quantity": "1",   "unit": "tsp",   "name": "chili powder"},
            {"quantity": "1",   "unit": "",      "name": "bay leaf"},
            {"quantity": "1/2", "unit": "cup",   "name": "plain yogurt"},
            {"quantity": "1.5", "unit": "cups",  "name": "heavy cream"},
            {"quantity": "2",   "unit": "tbsp",  "name": "garam masala"},
            {"quantity": "1",   "unit": "large", "name": "onion"},
            {"quantity": "1",   "unit": "bunch", "name": "cilantro"},
            {"quantity": "",    "unit": "handful","name": "cashews, ground"},
            {"quantity": "1",   "unit": "",      "name": "lemon, juiced"},
        ],
        "steps": [
            "Combine all marinade ingredients and pour over the chicken. Marinate for at least 4 hours or overnight.",
            "Bring the chicken to room temperature about 1 hour before cooking.",
            "Preheat oven to 525°F. Remove chicken from marinade and place on a wire rack over a foil-lined baking sheet. Roast for 25–30 minutes, flipping halfway through, until nicely charred on all sides.",
            "For the sauce: blend the onion, green chilies, and ginger garlic paste in a food processor until smooth.",
            "Heat 1 tablespoon oil in a large saucepan over medium-high heat. Sauté the onion mixture until soft and translucent. Stir in the butter and lemon juice.",
            "Add all the spices and cook for 5 minutes, stirring constantly, until fragrant and a dark masala forms. Do not let it burn.",
            "Add the tomato puree and cook for 2 minutes, stirring frequently. Stir in the heavy cream and yogurt. Reduce heat to low, add the bay leaf, and simmer for 10 minutes, stirring often. Season with salt and pepper. If the sauce seems thin, stir in the ground cashews.",
            "Add the roasted tandoori chicken to the sauce and simmer on low until fully incorporated. Taste and adjust seasoning.",
            "Garnish with chopped cilantro and serve with basmati rice or naan.",
        ],
    },

]
